### ISSUE TITLE
[Fix] Trim attribute value to 128 symbols

### ISSUE THREAD

**Issue by dummyuser992** [reportportal/commons-model#317]
Since the server allows attributes value only up to 128 symbols, all items with attributes value of more than 128 characters will not be created in ReportPortal at all. 

The suggestion is just to trim the value by 128 symbols.

The issue is similar to [this](https://github.com/reportportal/client-net/issues/57), but for the Java client.
The PR is [here](https://github.com/reportportal/commons-model/pull/316).

**Comment by miracle8484** [comment]
Hello, could you clarify your intention - you want to write just part attribute, in case it has more than 128 symbols  and don't tell anything to client, am i right?
If yes, than unfortunately it's inappropriate, because it will be the source of potential bugs, when client sends some data and wait one behavior, but have another.

**Comment by dummyuser992** [comment]
Hi! Could you please contact me in Teams - Anton_Yehorov@epam.com?

**Comment by dummyuser992** [comment]
Decided to move to agent levels
